### ISSUE TITLE
iris-embedded-python-wrapper version 0.0.3

### ISSUE THREAD

**Issue by grongierisc** [intersystems-community/intersystems-irispython#4]
this driver is using iris-embedded-python-wrapper version 0.0.3

version 0.0.4 bring ipm fix

version 0.0.5 bring a workaround for iris module changing the working directory to the main database folder.

```python
>>> import os
>>> os.getcwd()
'/irisdev/app'
>>> import iris
>>> os.getcwd()
'/usr/irissys/mgr/IRISAPP_DATA'
>>> iris.system.Version.GetVersion()
'IRIS for UNIX (Ubuntu Server LTS for x86-64 Containers) 2023.1 (Build 229U) Fri Apr 14 2023 17:37:52 EDT'
```

with 0.0.5 os.getcwd() won't change.

Can you test on your side if bumping to iris-embedded-python-wrapper to 0.0.5 won't break any thing, if so update the requirements ?

**Comment by daimor** [comment]
done
